### ISSUE TITLE
Find a new project name

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#13]
The current project’s name ‘Public API Data Processing’ does not really reflect our actual intention with the project.

The new name should be an indicator for what to expect from the project.

**Comment by wkrl** [comment]
OpenCities - Open Data Visualizer for Cities
Offene Daten App

**Comment by pthrrr** [comment]
Ich habe an sowas hier gedacht:
- City Data Hub

- City Data Portal

- City Data Visualizer

**Comment by anasalhakim** [comment]
Finde den Namen "**Citylizer**" cool :)
So eine Kombination zwischen City und Visualizer.

**Comment by pthrrr** [comment]
> Finde den Namen "**Citylizer**" cool :)
> So eine Kombination zwischen City und Visualizer.

Ja der ist cool, aber der hat keine große Aussagekraft.
Wir bauchen ja einen Namen der genau das beschreibt was unsere Webseite macht. Zumindest wurde das von den Dozenten gewünscht.

**Comment by kat-hi** [comment]
Ich finde "health" müsste noch Platz finden.
- City Health Data Hub/Visualizer
- Citylizer - Health Data Hub
- Open Health Data Visualizer

**Comment by anasalhakim** [comment]
> * Citylizer - Health Data Hub

Finde "Citylizer - Health Data Hub" Sinnvoll .. man könnte in Design Citylizer als Haupt Logo nehmen und Health Data Hub als kleiner Satz daneben.

**Comment by ali-260011** [comment]
- City Health Hub (CHH).
- Healthy City Hub :D 

- Als wir auch das Projekt nicht nur mit Health Dinge begrenzen werden, würde ich "City Open Hub", empfehlen.

**Comment by dismaien** [comment]
_City Health Hub_ finde ich auch gut! _Citylizer_ wäre dann ja eher in Richtung "brand name", momentan suchen wir ja (so habe ich es zumindest verstanden) einen deskriptiven WIP Projektnamen.
Für mich war bisher noch nicht klar, ob dieser Fokus auf Health sich nun wirklich durch das ganze Projekt zieht, dachte es betrifft vielleicht eher unsere Anfangsdaten, aber halte es an sich auch für ein gutes (und aktuelles...) Thema, also warum nicht.
Wenn man ähnliche Wortkombinationen allerdings googelt, geht es bei ähnlicher Begrifflichkeit oft eher um Healthcare, könnte also vielleicht auch etwas missverständlich sein. Falls wir allgemeiner bleiben, fände ich _Open City Visualizer_ o.ä. gut, open im Namen würde auch die inhaltliche Herangehensweise und Positionierung zu open data unterstützen

**Comment by ali-260011** [comment]
> _City Health Hub_ finde ich auch gut! _Citylizer_ wäre dann ja eher in Richtung "brand name", momentan suchen wir ja (so habe ich es zumindest verstanden) einen deskriptiven WIP Projektnamen.
> Für mich war bisher noch nicht klar, ob dieser Fokus auf Health sich nun wirklich durch das ganze Projekt zieht, dachte es betrifft vielleicht eher unsere Anfangsdaten, aber halte es an sich auch für ein gutes (und aktuelles...) Thema, also warum nicht.
> Wenn man ähnliche Wortkombinationen allerdings googelt, geht es bei ähnlicher Begrifflichkeit oft eher um Healthcare, könnte also vielleicht auch etwas missverständlich sein. Falls wir allgemeiner bleiben, fände ich _Open City Visualizer_ o.ä. gut, open im Namen würde auch die inhaltliche Herangehensweise und Positionierung zu open data unterstützen

Das stimmt, das Projekt soll verallgemeinert werden nachher und nicht nur um Covid19 gehen.
