### ISSUE TITLE
(s34) implement api endpoint for the webserver that provides geojson object for berlin's districts for requested day

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#31]
story: https://github.com/Api-visualizer/api-visualizer-FE/issues/34
database service has to read the information from the database and has to respond to the webserver that wants to show a shape map with districts and covid data

**Comment by wkrl** [comment]
@pierrefabarius @NikRup i'm changing the purpose of this task, since we don't have the monthly view yet - just daily. this should return a geojson object that is stored in the database for a requested date.
