### ISSUE TITLE
(s34) implement geojson shapes for berlin districts that are clickable and display feature properties

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#32]
There should be district shapes with a color. Those should also be clickable and show the district's feature data.

story: https://github.com/Api-visualizer/api-visualizer-FE/issues/34

**Comment by wkrl** [comment]
@dismaien @kat-hi i'm changing the purpose of this task, since we don't have the monthly view yet - just daily. we can implement a bar chart later; then for berlin districts + the other cities.
