### ISSUE TITLE
create specific project vision

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#56]
we need a document that manifests the vision:

TODOs aus Dozenten-Meeting:
Datenmenge inhaltlich weiter einschränken, evtl. Fokus aus Gesundheit und Soziales als Sparten?
Überlegung: Wer ist unser Kunde? Bürgerservice --> Stadt als Kunde?

**Comment by wkrl** [comment]
City Data Visualizer is a modern web app that provides helpful visualizations for complex health data. With the help of open data, we hope to give both Berlin's administration and scientists a better understanding of current health risks or positive impacts that are occurring in the city.
